# Generated by Django 3.2.15 on 2023-12-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('lat', models.FloatField(verbose_name='Координаты: широта')),
                ('lon', models.FloatField(verbose_name='Координаты: долгота')),
                ('request_datetime', models.DateTimeField(verbose_name='Дата запроса к API geopy')),
            ],
        ),
    ]
