# Generated by Django 3.2.15 on 2023-12-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Координаты: широта'),
        ),
        migrations.AlterField(
            model_name='places',
            name='lon',
            field=models.FloatField(null=True, verbose_name='Координаты: долгота'),
        ),
    ]
