# Generated by Django 3.2.15 on 2023-06-14 19:57

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_orderdetails_orderedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproducts',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0, 0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона'),
        ),
    ]
