# Generated by Django 3.2.15 on 2023-08-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_orderedproducts_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('1', 'Не обработан'), ('2', 'Не собран'), ('3', 'Не доставлен'), ('4', 'Доставлен')], db_index=True, default='1', max_length=2),
        ),
    ]
