# Generated by Django 3.2.15 on 2023-08-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='комментарий к заказу'),
        ),
    ]
