# Generated by Django 3.2.15 on 2023-08-09 20:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_orderdetails_register_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='payment_method',
            field=models.CharField(choices=[('CS', 'Наличностью'), ('EL', 'Электронно')], db_index=True, default='CS', max_length=2, verbose_name='метод оплаты'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 20, 37, 59, 642686, tzinfo=utc), verbose_name='время заказа'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('1', 'Не обработан'), ('2', 'Не собран'), ('3', 'Не доставлен'), ('4', 'Доставлен')], db_index=True, default='1', max_length=2, verbose_name='статус заказа'),
        ),
    ]
