# Generated by Django 3.2.15 on 2023-09-17 19:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20230809_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='capable_restaurants',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Возможные рестораны'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='chosen_restaurant',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='foodcartapp.restaurant', verbose_name='ресторан'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 19, 42, 2, 173155, tzinfo=utc), verbose_name='время заказа'),
        ),
    ]
