# Generated by Django 3.2.15 on 2023-12-14 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20231202_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='payment_method',
            field=models.CharField(choices=[('ND', 'Не определен'), ('CS', 'Наличностью'), ('EL', 'Электронно')], db_index=True, default='ND', max_length=2, verbose_name='метод оплаты'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 17, 31, 22, 529399, tzinfo=utc), verbose_name='время заказа'),
        ),
    ]
