# Generated by Django 3.2.15 on 2023-12-14 17:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20231214_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='chosen_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='foodcartapp.restaurant', verbose_name='ресторан'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 17, 33, 32, 499907, tzinfo=utc), verbose_name='время заказа'),
        ),
    ]
