# Generated by Django 3.2.15 on 2023-12-14 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20231214_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='комментарий к заказу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 17, 56, 37, 228215, tzinfo=utc), verbose_name='время заказа'),
        ),
    ]
