# Generated by Django 3.2.15 on 2023-12-14 18:03

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20231214_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 18, 3, 44, 376253, tzinfo=utc), verbose_name='время заказа'),
        ),
        migrations.AlterField(
            model_name='orderedproducts',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество'),
        ),
    ]
