# Generated by Django 3.2.15 on 2023-12-14 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20231214_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 18, 6, 35, 114044, tzinfo=utc), verbose_name='время заказа'),
        ),
    ]
